[build]
target = 'avr-none'
rustflags = ["-C", "target-cpu=atmega2560"]

[test]
target = "aarch64-apple-darwin"

[target.aarch64-apple-darwin]
runner = "simavr"

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 115200"

[unstable]
build-std = ["core", "alloc"]
